=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::MerchantFulfillmentApiModel
  # A shipping service offer made by a carrier.
  class ShippingService
    # A plain text representation of a carrier's shipping service. For example, \"UPS Ground\" or \"FedEx Standard Overnight\". 
    attr_accessor :shipping_service_name

    # The name of the carrier.
    attr_accessor :carrier_name

    attr_accessor :shipping_service_id

    # An Amazon-defined shipping service offer identifier.
    attr_accessor :shipping_service_offer_id

    # The date that the carrier will ship the package.
    attr_accessor :ship_date

    # The earliest date by which the shipment will be delivered.
    attr_accessor :earliest_estimated_delivery_date

    # The latest date by which the shipment will be delivered.
    attr_accessor :latest_estimated_delivery_date

    # The amount that the carrier will charge for the shipment.
    attr_accessor :rate

    # Extra services offered by the carrier.
    attr_accessor :shipping_service_options

    attr_accessor :available_shipping_service_options

    attr_accessor :available_label_formats

    attr_accessor :available_format_options_for_label

    # When true, additional seller inputs are required.
    attr_accessor :requires_additional_seller_inputs


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'shipping_service_name' => :'ShippingServiceName',
        :'carrier_name' => :'CarrierName',
        :'shipping_service_id' => :'ShippingServiceId',
        :'shipping_service_offer_id' => :'ShippingServiceOfferId',
        :'ship_date' => :'ShipDate',
        :'earliest_estimated_delivery_date' => :'EarliestEstimatedDeliveryDate',
        :'latest_estimated_delivery_date' => :'LatestEstimatedDeliveryDate',
        :'rate' => :'Rate',
        :'shipping_service_options' => :'ShippingServiceOptions',
        :'available_shipping_service_options' => :'AvailableShippingServiceOptions',
        :'available_label_formats' => :'AvailableLabelFormats',
        :'available_format_options_for_label' => :'AvailableFormatOptionsForLabel',
        :'requires_additional_seller_inputs' => :'RequiresAdditionalSellerInputs'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'shipping_service_name' => :'String',
        :'carrier_name' => :'String',
        :'shipping_service_id' => :'ShippingServiceIdentifier',
        :'shipping_service_offer_id' => :'String',
        :'ship_date' => :'Timestamp',
        :'earliest_estimated_delivery_date' => :'Timestamp',
        :'latest_estimated_delivery_date' => :'Timestamp',
        :'rate' => :'CurrencyAmount',
        :'shipping_service_options' => :'ShippingServiceOptions',
        :'available_shipping_service_options' => :'AvailableShippingServiceOptions',
        :'available_label_formats' => :'LabelFormatList',
        :'available_format_options_for_label' => :'AvailableFormatOptionsForLabelList',
        :'requires_additional_seller_inputs' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ShippingServiceName')
        self.shipping_service_name = attributes[:'ShippingServiceName']
      end

      if attributes.has_key?(:'CarrierName')
        self.carrier_name = attributes[:'CarrierName']
      end

      if attributes.has_key?(:'ShippingServiceId')
        self.shipping_service_id = attributes[:'ShippingServiceId']
      end

      if attributes.has_key?(:'ShippingServiceOfferId')
        self.shipping_service_offer_id = attributes[:'ShippingServiceOfferId']
      end

      if attributes.has_key?(:'ShipDate')
        self.ship_date = attributes[:'ShipDate']
      end

      if attributes.has_key?(:'EarliestEstimatedDeliveryDate')
        self.earliest_estimated_delivery_date = attributes[:'EarliestEstimatedDeliveryDate']
      end

      if attributes.has_key?(:'LatestEstimatedDeliveryDate')
        self.latest_estimated_delivery_date = attributes[:'LatestEstimatedDeliveryDate']
      end

      if attributes.has_key?(:'Rate')
        self.rate = attributes[:'Rate']
      end

      if attributes.has_key?(:'ShippingServiceOptions')
        self.shipping_service_options = attributes[:'ShippingServiceOptions']
      end

      if attributes.has_key?(:'AvailableShippingServiceOptions')
        self.available_shipping_service_options = attributes[:'AvailableShippingServiceOptions']
      end

      if attributes.has_key?(:'AvailableLabelFormats')
        self.available_label_formats = attributes[:'AvailableLabelFormats']
      end

      if attributes.has_key?(:'AvailableFormatOptionsForLabel')
        self.available_format_options_for_label = attributes[:'AvailableFormatOptionsForLabel']
      end

      if attributes.has_key?(:'RequiresAdditionalSellerInputs')
        self.requires_additional_seller_inputs = attributes[:'RequiresAdditionalSellerInputs']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @shipping_service_name.nil?
      return false if @carrier_name.nil?
      return false if @shipping_service_id.nil?
      return false if @shipping_service_offer_id.nil?
      return false if @ship_date.nil?
      return false if @rate.nil?
      return false if @shipping_service_options.nil?
      return false if @requires_additional_seller_inputs.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          shipping_service_name == o.shipping_service_name &&
          carrier_name == o.carrier_name &&
          shipping_service_id == o.shipping_service_id &&
          shipping_service_offer_id == o.shipping_service_offer_id &&
          ship_date == o.ship_date &&
          earliest_estimated_delivery_date == o.earliest_estimated_delivery_date &&
          latest_estimated_delivery_date == o.latest_estimated_delivery_date &&
          rate == o.rate &&
          shipping_service_options == o.shipping_service_options &&
          available_shipping_service_options == o.available_shipping_service_options &&
          available_label_formats == o.available_label_formats &&
          available_format_options_for_label == o.available_format_options_for_label &&
          requires_additional_seller_inputs == o.requires_additional_seller_inputs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [shipping_service_name, carrier_name, shipping_service_id, shipping_service_offer_id, ship_date, earliest_estimated_delivery_date, latest_estimated_delivery_date, rate, shipping_service_options, available_shipping_service_options, available_label_formats, available_format_options_for_label, requires_additional_seller_inputs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::MerchantFulfillmentApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
