=begin
#Selling Partner API for Services

#With the Services API, you can build applications that help service providers get and modify their service orders.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::ServicesApiModel
  # The job details of a service.
  class ServiceJob
    # The date and time of the creation of the job, in ISO 8601 format.
    attr_accessor :create_time

    # The service job identifier.
    attr_accessor :service_job_id

    # The status of the service job.
    attr_accessor :service_job_status

    # The scope of work for the order.
    attr_accessor :scope_of_work

    # Information about the seller of the service job.
    attr_accessor :seller

    # Information about the service job provider.
    attr_accessor :service_job_provider

    # A list of appointment windows preferred by the buyer. Included only if the buyer selected appointment windows when creating the order.
    attr_accessor :preferred_appointment_times

    # A list of appointments.
    attr_accessor :appointments

    # The Amazon-defined identifier for an order placed by the buyer, in 3-7-7 format.
    attr_accessor :service_order_id

    # The marketplace identifier.
    attr_accessor :marketplace_id

    # Information about the buyer.
    attr_accessor :buyer

    # A list of items associated with the service job.
    attr_accessor :associated_items

    # Information about the location of the service job.
    attr_accessor :service_location

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'create_time' => :'createTime',
        :'service_job_id' => :'serviceJobId',
        :'service_job_status' => :'serviceJobStatus',
        :'scope_of_work' => :'scopeOfWork',
        :'seller' => :'seller',
        :'service_job_provider' => :'serviceJobProvider',
        :'preferred_appointment_times' => :'preferredAppointmentTimes',
        :'appointments' => :'appointments',
        :'service_order_id' => :'serviceOrderId',
        :'marketplace_id' => :'marketplaceId',
        :'buyer' => :'buyer',
        :'associated_items' => :'associatedItems',
        :'service_location' => :'serviceLocation'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'create_time' => :'DateTime',
        :'service_job_id' => :'ServiceJobId',
        :'service_job_status' => :'String',
        :'scope_of_work' => :'ScopeOfWork',
        :'seller' => :'Seller',
        :'service_job_provider' => :'ServiceJobProvider',
        :'preferred_appointment_times' => :'Array<AppointmentTime>',
        :'appointments' => :'Array<Appointment>',
        :'service_order_id' => :'OrderId',
        :'marketplace_id' => :'String',
        :'buyer' => :'Buyer',
        :'associated_items' => :'Array<AssociatedItem>',
        :'service_location' => :'ServiceLocation'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'createTime')
        self.create_time = attributes[:'createTime']
      end

      if attributes.has_key?(:'serviceJobId')
        self.service_job_id = attributes[:'serviceJobId']
      end

      if attributes.has_key?(:'serviceJobStatus')
        self.service_job_status = attributes[:'serviceJobStatus']
      end

      if attributes.has_key?(:'scopeOfWork')
        self.scope_of_work = attributes[:'scopeOfWork']
      end

      if attributes.has_key?(:'seller')
        self.seller = attributes[:'seller']
      end

      if attributes.has_key?(:'serviceJobProvider')
        self.service_job_provider = attributes[:'serviceJobProvider']
      end

      if attributes.has_key?(:'preferredAppointmentTimes')
        if (value = attributes[:'preferredAppointmentTimes']).is_a?(Array)
          self.preferred_appointment_times = value
        end
      end

      if attributes.has_key?(:'appointments')
        if (value = attributes[:'appointments']).is_a?(Array)
          self.appointments = value
        end
      end

      if attributes.has_key?(:'serviceOrderId')
        self.service_order_id = attributes[:'serviceOrderId']
      end

      if attributes.has_key?(:'marketplaceId')
        self.marketplace_id = attributes[:'marketplaceId']
      end

      if attributes.has_key?(:'buyer')
        self.buyer = attributes[:'buyer']
      end

      if attributes.has_key?(:'associatedItems')
        if (value = attributes[:'associatedItems']).is_a?(Array)
          self.associated_items = value
        end
      end

      if attributes.has_key?(:'serviceLocation')
        self.service_location = attributes[:'serviceLocation']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new

      if !@marketplace_id.nil? && @marketplace_id !~ Regexp.new(^[A-Z0-9]*$)
        invalid_properties.push("invalid value for 'marketplace_id', must conform to the pattern ^[A-Z0-9]*$.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      service_job_status_validator = EnumAttributeValidator.new('String', ["NOT_SERVICED", "CANCELLED", "COMPLETED", "PENDING_SCHEDULE", "NOT_FULFILLABLE", "HOLD", "PAYMENT_DECLINED"])
      return false unless service_job_status_validator.valid?(@service_job_status)
      return false if !@marketplace_id.nil? && @marketplace_id !~ Regexp.new(^[A-Z0-9]*$)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] service_job_status Object to be assigned
    def service_job_status=(service_job_status)
      validator = EnumAttributeValidator.new('String', ["NOT_SERVICED", "CANCELLED", "COMPLETED", "PENDING_SCHEDULE", "NOT_FULFILLABLE", "HOLD", "PAYMENT_DECLINED"])
      unless validator.valid?(service_job_status)
        fail ArgumentError, "invalid value for 'service_job_status', must be one of #{validator.allowable_values}."
      end
      @service_job_status = service_job_status
    end

    # Custom attribute writer method with validation
    # @param [Object] marketplace_id Value to be assigned
    def marketplace_id=(marketplace_id)

      if !marketplace_id.nil? && marketplace_id !~ Regexp.new(^[A-Z0-9]*$)
        fail ArgumentError, "invalid value for 'marketplace_id', must conform to the pattern ^[A-Z0-9]*$."
      end

      @marketplace_id = marketplace_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          create_time == o.create_time &&
          service_job_id == o.service_job_id &&
          service_job_status == o.service_job_status &&
          scope_of_work == o.scope_of_work &&
          seller == o.seller &&
          service_job_provider == o.service_job_provider &&
          preferred_appointment_times == o.preferred_appointment_times &&
          appointments == o.appointments &&
          service_order_id == o.service_order_id &&
          marketplace_id == o.marketplace_id &&
          buyer == o.buyer &&
          associated_items == o.associated_items &&
          service_location == o.service_location
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [create_time, service_job_id, service_job_status, scope_of_work, seller, service_job_provider, preferred_appointment_times, appointments, service_order_id, marketplace_id, buyer, associated_items, service_location].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::ServicesApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
