=begin
#Selling Partner API for Finances

#The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::FinancesApiModel
  # A credit given to a solution provider.
  class SolutionProviderCreditEvent
    # The transaction type.
    attr_accessor :provider_transaction_type

    # A seller-defined identifier for an order.
    attr_accessor :seller_order_id

    # The identifier of the marketplace where the order was placed.
    attr_accessor :marketplace_id

    # The two-letter country code of the country associated with the marketplace where the order was placed.
    attr_accessor :marketplace_country_code

    # The Amazon-defined identifier of the seller.
    attr_accessor :seller_id

    # The store name where the payment event occurred.
    attr_accessor :seller_store_name

    # The Amazon-defined identifier of the solution provider.
    attr_accessor :provider_id

    # The store name where the payment event occurred.
    attr_accessor :provider_store_name

    # The amount of the credit.
    attr_accessor :transaction_amount

    # The date and time that the credit transaction was created, in ISO 8601 date time format.
    attr_accessor :transaction_creation_date


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'provider_transaction_type' => :'ProviderTransactionType',
        :'seller_order_id' => :'SellerOrderId',
        :'marketplace_id' => :'MarketplaceId',
        :'marketplace_country_code' => :'MarketplaceCountryCode',
        :'seller_id' => :'SellerId',
        :'seller_store_name' => :'SellerStoreName',
        :'provider_id' => :'ProviderId',
        :'provider_store_name' => :'ProviderStoreName',
        :'transaction_amount' => :'TransactionAmount',
        :'transaction_creation_date' => :'TransactionCreationDate'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'provider_transaction_type' => :'String',
        :'seller_order_id' => :'String',
        :'marketplace_id' => :'String',
        :'marketplace_country_code' => :'String',
        :'seller_id' => :'String',
        :'seller_store_name' => :'String',
        :'provider_id' => :'String',
        :'provider_store_name' => :'String',
        :'transaction_amount' => :'Currency',
        :'transaction_creation_date' => :'Date'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ProviderTransactionType')
        self.provider_transaction_type = attributes[:'ProviderTransactionType']
      end

      if attributes.has_key?(:'SellerOrderId')
        self.seller_order_id = attributes[:'SellerOrderId']
      end

      if attributes.has_key?(:'MarketplaceId')
        self.marketplace_id = attributes[:'MarketplaceId']
      end

      if attributes.has_key?(:'MarketplaceCountryCode')
        self.marketplace_country_code = attributes[:'MarketplaceCountryCode']
      end

      if attributes.has_key?(:'SellerId')
        self.seller_id = attributes[:'SellerId']
      end

      if attributes.has_key?(:'SellerStoreName')
        self.seller_store_name = attributes[:'SellerStoreName']
      end

      if attributes.has_key?(:'ProviderId')
        self.provider_id = attributes[:'ProviderId']
      end

      if attributes.has_key?(:'ProviderStoreName')
        self.provider_store_name = attributes[:'ProviderStoreName']
      end

      if attributes.has_key?(:'TransactionAmount')
        self.transaction_amount = attributes[:'TransactionAmount']
      end

      if attributes.has_key?(:'TransactionCreationDate')
        self.transaction_creation_date = attributes[:'TransactionCreationDate']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          provider_transaction_type == o.provider_transaction_type &&
          seller_order_id == o.seller_order_id &&
          marketplace_id == o.marketplace_id &&
          marketplace_country_code == o.marketplace_country_code &&
          seller_id == o.seller_id &&
          seller_store_name == o.seller_store_name &&
          provider_id == o.provider_id &&
          provider_store_name == o.provider_store_name &&
          transaction_amount == o.transaction_amount &&
          transaction_creation_date == o.transaction_creation_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [provider_transaction_type, seller_order_id, marketplace_id, marketplace_country_code, seller_id, seller_store_name, provider_id, provider_store_name, transaction_amount, transaction_creation_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::FinancesApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
