=begin
#Selling Partner API for Retail Procurement Orders

#The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::VendorOrdersApiModel
  # Current status of a purchase order.
  class OrderStatus
    # The buyer's purchase order number for this order. Formatting Notes: 8-character alpha-numeric code.
    attr_accessor :purchase_order_number

    # The status of the buyer's purchase order for this order.
    attr_accessor :purchase_order_status

    # The date the purchase order was placed. Must be in ISO-8601 date/time format.
    attr_accessor :purchase_order_date

    # The date when the purchase order was last updated. Must be in ISO-8601 date/time format.
    attr_accessor :last_updated_date

    # Name/Address and tax details of the selling party.
    attr_accessor :selling_party

    # Name/Address and tax details of the ship to party.
    attr_accessor :ship_to_party

    # Detailed order status.
    attr_accessor :item_status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'purchase_order_number' => :'purchaseOrderNumber',
        :'purchase_order_status' => :'purchaseOrderStatus',
        :'purchase_order_date' => :'purchaseOrderDate',
        :'last_updated_date' => :'lastUpdatedDate',
        :'selling_party' => :'sellingParty',
        :'ship_to_party' => :'shipToParty',
        :'item_status' => :'itemStatus'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'purchase_order_number' => :'String',
        :'purchase_order_status' => :'String',
        :'purchase_order_date' => :'DateTime',
        :'last_updated_date' => :'DateTime',
        :'selling_party' => :'PartyIdentification',
        :'ship_to_party' => :'PartyIdentification',
        :'item_status' => :'ItemStatus'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'purchaseOrderNumber')
        self.purchase_order_number = attributes[:'purchaseOrderNumber']
      end

      if attributes.has_key?(:'purchaseOrderStatus')
        self.purchase_order_status = attributes[:'purchaseOrderStatus']
      end

      if attributes.has_key?(:'purchaseOrderDate')
        self.purchase_order_date = attributes[:'purchaseOrderDate']
      end

      if attributes.has_key?(:'lastUpdatedDate')
        self.last_updated_date = attributes[:'lastUpdatedDate']
      end

      if attributes.has_key?(:'sellingParty')
        self.selling_party = attributes[:'sellingParty']
      end

      if attributes.has_key?(:'shipToParty')
        self.ship_to_party = attributes[:'shipToParty']
      end

      if attributes.has_key?(:'itemStatus')
        self.item_status = attributes[:'itemStatus']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @purchase_order_number.nil?
      return false if @purchase_order_status.nil?
      purchase_order_status_validator = EnumAttributeValidator.new('String', ["OPEN", "CLOSED"])
      return false unless purchase_order_status_validator.valid?(@purchase_order_status)
      return false if @purchase_order_date.nil?
      return false if @selling_party.nil?
      return false if @ship_to_party.nil?
      return false if @item_status.nil?
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] purchase_order_status Object to be assigned
    def purchase_order_status=(purchase_order_status)
      validator = EnumAttributeValidator.new('String', ["OPEN", "CLOSED"])
      unless validator.valid?(purchase_order_status)
        fail ArgumentError, "invalid value for 'purchase_order_status', must be one of #{validator.allowable_values}."
      end
      @purchase_order_status = purchase_order_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          purchase_order_number == o.purchase_order_number &&
          purchase_order_status == o.purchase_order_status &&
          purchase_order_date == o.purchase_order_date &&
          last_updated_date == o.last_updated_date &&
          selling_party == o.selling_party &&
          ship_to_party == o.ship_to_party &&
          item_status == o.item_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [purchase_order_number, purchase_order_status, purchase_order_date, last_updated_date, selling_party, ship_to_party, item_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::VendorOrdersApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
