=begin
#Selling Partner APIs for Fulfillment Outbound

#The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

OpenAPI spec version: 2020-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::FulfillmentOutboundApiModel
  class AdditionalLocationInfo
    
    AS_INSTRUCTED = "AS_INSTRUCTED".freeze
    CARPORT = "CARPORT".freeze
    CUSTOMER_PICKUP = "CUSTOMER_PICKUP".freeze
    DECK = "DECK".freeze
    DOOR_PERSON = "DOOR_PERSON".freeze
    FRONT_DESK = "FRONT_DESK".freeze
    FRONT_DOOR = "FRONT_DOOR".freeze
    GARAGE = "GARAGE".freeze
    GUARD = "GUARD".freeze
    MAIL_ROOM = "MAIL_ROOM".freeze
    MAIL_SLOT = "MAIL_SLOT".freeze
    MAILBOX = "MAILBOX".freeze
    MC_BOY = "MC_BOY".freeze
    MC_GIRL = "MC_GIRL".freeze
    MC_MAN = "MC_MAN".freeze
    MC_WOMAN = "MC_WOMAN".freeze
    NEIGHBOR = "NEIGHBOR".freeze
    OFFICE = "OFFICE".freeze
    OUTBUILDING = "OUTBUILDING".freeze
    PATIO = "PATIO".freeze
    PORCH = "PORCH".freeze
    REAR_DOOR = "REAR_DOOR".freeze
    RECEPTIONIST = "RECEPTIONIST".freeze
    RECEIVER = "RECEIVER".freeze
    SECURE_LOCATION = "SECURE_LOCATION".freeze
    SIDE_DOOR = "SIDE_DOOR".freeze
  end

end
