=begin
#Selling Partner APIs for Fulfillment Outbound

#The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

OpenAPI spec version: 2020-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.26

=end

require 'date'

module AmzSpApi::FulfillmentOutboundApiModel
  # An item that Amazon accepted for return.
  class ReturnItem
    # An identifier assigned by the seller to the return item.
    attr_accessor :seller_return_item_id

    # The identifier assigned to the item by the seller when the fulfillment order was created.
    attr_accessor :seller_fulfillment_order_item_id

    # The identifier for the shipment that is associated with the return item.
    attr_accessor :amazon_shipment_id

    # The return reason code assigned to the return item by the seller.
    attr_accessor :seller_return_reason_code

    # An optional comment about the return item.
    attr_accessor :return_comment

    # The return reason code that the Amazon fulfillment center assigned to the return item.
    attr_accessor :amazon_return_reason_code

    # Indicates if the return item has been processed by an Amazon fulfillment center.
    attr_accessor :status

    # Indicates when the status last changed.
    attr_accessor :status_changed_date

    # Identifies the return authorization used to return this item. See ReturnAuthorization.
    attr_accessor :return_authorization_id

    attr_accessor :return_received_condition

    # The identifier for the Amazon fulfillment center that processed the return item.
    attr_accessor :fulfillment_center_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'seller_return_item_id' => :'sellerReturnItemId',
        :'seller_fulfillment_order_item_id' => :'sellerFulfillmentOrderItemId',
        :'amazon_shipment_id' => :'amazonShipmentId',
        :'seller_return_reason_code' => :'sellerReturnReasonCode',
        :'return_comment' => :'returnComment',
        :'amazon_return_reason_code' => :'amazonReturnReasonCode',
        :'status' => :'status',
        :'status_changed_date' => :'statusChangedDate',
        :'return_authorization_id' => :'returnAuthorizationId',
        :'return_received_condition' => :'returnReceivedCondition',
        :'fulfillment_center_id' => :'fulfillmentCenterId'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'seller_return_item_id' => :'String',
        :'seller_fulfillment_order_item_id' => :'String',
        :'amazon_shipment_id' => :'String',
        :'seller_return_reason_code' => :'String',
        :'return_comment' => :'String',
        :'amazon_return_reason_code' => :'String',
        :'status' => :'FulfillmentReturnItemStatus',
        :'status_changed_date' => :'Timestamp',
        :'return_authorization_id' => :'String',
        :'return_received_condition' => :'ReturnItemDisposition',
        :'fulfillment_center_id' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'sellerReturnItemId')
        self.seller_return_item_id = attributes[:'sellerReturnItemId']
      end

      if attributes.has_key?(:'sellerFulfillmentOrderItemId')
        self.seller_fulfillment_order_item_id = attributes[:'sellerFulfillmentOrderItemId']
      end

      if attributes.has_key?(:'amazonShipmentId')
        self.amazon_shipment_id = attributes[:'amazonShipmentId']
      end

      if attributes.has_key?(:'sellerReturnReasonCode')
        self.seller_return_reason_code = attributes[:'sellerReturnReasonCode']
      end

      if attributes.has_key?(:'returnComment')
        self.return_comment = attributes[:'returnComment']
      end

      if attributes.has_key?(:'amazonReturnReasonCode')
        self.amazon_return_reason_code = attributes[:'amazonReturnReasonCode']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'statusChangedDate')
        self.status_changed_date = attributes[:'statusChangedDate']
      end

      if attributes.has_key?(:'returnAuthorizationId')
        self.return_authorization_id = attributes[:'returnAuthorizationId']
      end

      if attributes.has_key?(:'returnReceivedCondition')
        self.return_received_condition = attributes[:'returnReceivedCondition']
      end

      if attributes.has_key?(:'fulfillmentCenterId')
        self.fulfillment_center_id = attributes[:'fulfillmentCenterId']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @seller_return_item_id.nil?
        invalid_properties.push('invalid value for "seller_return_item_id", seller_return_item_id cannot be nil.')
      end

      if @seller_fulfillment_order_item_id.nil?
        invalid_properties.push('invalid value for "seller_fulfillment_order_item_id", seller_fulfillment_order_item_id cannot be nil.')
      end

      if @amazon_shipment_id.nil?
        invalid_properties.push('invalid value for "amazon_shipment_id", amazon_shipment_id cannot be nil.')
      end

      if @seller_return_reason_code.nil?
        invalid_properties.push('invalid value for "seller_return_reason_code", seller_return_reason_code cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @status_changed_date.nil?
        invalid_properties.push('invalid value for "status_changed_date", status_changed_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @seller_return_item_id.nil?
      return false if @seller_fulfillment_order_item_id.nil?
      return false if @amazon_shipment_id.nil?
      return false if @seller_return_reason_code.nil?
      return false if @status.nil?
      return false if @status_changed_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          seller_return_item_id == o.seller_return_item_id &&
          seller_fulfillment_order_item_id == o.seller_fulfillment_order_item_id &&
          amazon_shipment_id == o.amazon_shipment_id &&
          seller_return_reason_code == o.seller_return_reason_code &&
          return_comment == o.return_comment &&
          amazon_return_reason_code == o.amazon_return_reason_code &&
          status == o.status &&
          status_changed_date == o.status_changed_date &&
          return_authorization_id == o.return_authorization_id &&
          return_received_condition == o.return_received_condition &&
          fulfillment_center_id == o.fulfillment_center_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [seller_return_item_id, seller_fulfillment_order_item_id, amazon_shipment_id, seller_return_reason_code, return_comment, amazon_return_reason_code, status, status_changed_date, return_authorization_id, return_received_condition, fulfillment_center_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::FulfillmentOutboundApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
