=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module AmzSpApi::CatalogItemsApiModel
  # Specific variations of the item.
  class RelationshipType
    # The identifiers that uniquely identify the item that is related.
    attr_accessor :identifiers

    # The color variation of the item.
    attr_accessor :color

    # The edition variation of the item.
    attr_accessor :edition

    # The flavor variation of the item.
    attr_accessor :flavor

    # The gem type variations of the item.
    attr_accessor :gem_type

    # The golf club flex variation of an item.
    attr_accessor :golf_club_flex

    # The hand orientation variation of an item.
    attr_accessor :hand_orientation

    # The hardware platform variation of an item.
    attr_accessor :hardware_platform

    # The material type variations of an item.
    attr_accessor :material_type

    # The metal type variation of an item.
    attr_accessor :metal_type

    # The model variation of an item.
    attr_accessor :model

    # The operating system variations of an item.
    attr_accessor :operating_system

    # The product type subcategory variation of an item.
    attr_accessor :product_type_subcategory

    # The ring size variation of an item.
    attr_accessor :ring_size

    # The shaft material variation of an item.
    attr_accessor :shaft_material

    # The scent variation of an item.
    attr_accessor :scent

    # The size variation of an item.
    attr_accessor :size

    # The size per pearl variation of an item.
    attr_accessor :size_per_pearl

    # The golf club loft variation of an item.
    attr_accessor :golf_club_loft

    # The total diamond weight variation of an item.
    attr_accessor :total_diamond_weight

    # The total gem weight variation of an item.
    attr_accessor :total_gem_weight

    # The package quantity variation of an item.
    attr_accessor :package_quantity

    # The item dimensions relationship of an item.
    attr_accessor :item_dimensions


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'identifiers' => :'Identifiers',
        :'color' => :'Color',
        :'edition' => :'Edition',
        :'flavor' => :'Flavor',
        :'gem_type' => :'GemType',
        :'golf_club_flex' => :'GolfClubFlex',
        :'hand_orientation' => :'HandOrientation',
        :'hardware_platform' => :'HardwarePlatform',
        :'material_type' => :'MaterialType',
        :'metal_type' => :'MetalType',
        :'model' => :'Model',
        :'operating_system' => :'OperatingSystem',
        :'product_type_subcategory' => :'ProductTypeSubcategory',
        :'ring_size' => :'RingSize',
        :'shaft_material' => :'ShaftMaterial',
        :'scent' => :'Scent',
        :'size' => :'Size',
        :'size_per_pearl' => :'SizePerPearl',
        :'golf_club_loft' => :'GolfClubLoft',
        :'total_diamond_weight' => :'TotalDiamondWeight',
        :'total_gem_weight' => :'TotalGemWeight',
        :'package_quantity' => :'PackageQuantity',
        :'item_dimensions' => :'ItemDimensions'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'identifiers' => :'IdentifierType',
        :'color' => :'String',
        :'edition' => :'String',
        :'flavor' => :'String',
        :'gem_type' => :'Array<String>',
        :'golf_club_flex' => :'String',
        :'hand_orientation' => :'String',
        :'hardware_platform' => :'String',
        :'material_type' => :'Array<String>',
        :'metal_type' => :'String',
        :'model' => :'String',
        :'operating_system' => :'Array<String>',
        :'product_type_subcategory' => :'String',
        :'ring_size' => :'String',
        :'shaft_material' => :'String',
        :'scent' => :'String',
        :'size' => :'String',
        :'size_per_pearl' => :'String',
        :'golf_club_loft' => :'DecimalWithUnits',
        :'total_diamond_weight' => :'DecimalWithUnits',
        :'total_gem_weight' => :'DecimalWithUnits',
        :'package_quantity' => :'Integer',
        :'item_dimensions' => :'DimensionType'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'Identifiers')
        self.identifiers = attributes[:'Identifiers']
      end

      if attributes.has_key?(:'Color')
        self.color = attributes[:'Color']
      end

      if attributes.has_key?(:'Edition')
        self.edition = attributes[:'Edition']
      end

      if attributes.has_key?(:'Flavor')
        self.flavor = attributes[:'Flavor']
      end

      if attributes.has_key?(:'GemType')
        if (value = attributes[:'GemType']).is_a?(Array)
          self.gem_type = value
        end
      end

      if attributes.has_key?(:'GolfClubFlex')
        self.golf_club_flex = attributes[:'GolfClubFlex']
      end

      if attributes.has_key?(:'HandOrientation')
        self.hand_orientation = attributes[:'HandOrientation']
      end

      if attributes.has_key?(:'HardwarePlatform')
        self.hardware_platform = attributes[:'HardwarePlatform']
      end

      if attributes.has_key?(:'MaterialType')
        if (value = attributes[:'MaterialType']).is_a?(Array)
          self.material_type = value
        end
      end

      if attributes.has_key?(:'MetalType')
        self.metal_type = attributes[:'MetalType']
      end

      if attributes.has_key?(:'Model')
        self.model = attributes[:'Model']
      end

      if attributes.has_key?(:'OperatingSystem')
        if (value = attributes[:'OperatingSystem']).is_a?(Array)
          self.operating_system = value
        end
      end

      if attributes.has_key?(:'ProductTypeSubcategory')
        self.product_type_subcategory = attributes[:'ProductTypeSubcategory']
      end

      if attributes.has_key?(:'RingSize')
        self.ring_size = attributes[:'RingSize']
      end

      if attributes.has_key?(:'ShaftMaterial')
        self.shaft_material = attributes[:'ShaftMaterial']
      end

      if attributes.has_key?(:'Scent')
        self.scent = attributes[:'Scent']
      end

      if attributes.has_key?(:'Size')
        self.size = attributes[:'Size']
      end

      if attributes.has_key?(:'SizePerPearl')
        self.size_per_pearl = attributes[:'SizePerPearl']
      end

      if attributes.has_key?(:'GolfClubLoft')
        self.golf_club_loft = attributes[:'GolfClubLoft']
      end

      if attributes.has_key?(:'TotalDiamondWeight')
        self.total_diamond_weight = attributes[:'TotalDiamondWeight']
      end

      if attributes.has_key?(:'TotalGemWeight')
        self.total_gem_weight = attributes[:'TotalGemWeight']
      end

      if attributes.has_key?(:'PackageQuantity')
        self.package_quantity = attributes[:'PackageQuantity']
      end

      if attributes.has_key?(:'ItemDimensions')
        self.item_dimensions = attributes[:'ItemDimensions']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          identifiers == o.identifiers &&
          color == o.color &&
          edition == o.edition &&
          flavor == o.flavor &&
          gem_type == o.gem_type &&
          golf_club_flex == o.golf_club_flex &&
          hand_orientation == o.hand_orientation &&
          hardware_platform == o.hardware_platform &&
          material_type == o.material_type &&
          metal_type == o.metal_type &&
          model == o.model &&
          operating_system == o.operating_system &&
          product_type_subcategory == o.product_type_subcategory &&
          ring_size == o.ring_size &&
          shaft_material == o.shaft_material &&
          scent == o.scent &&
          size == o.size &&
          size_per_pearl == o.size_per_pearl &&
          golf_club_loft == o.golf_club_loft &&
          total_diamond_weight == o.total_diamond_weight &&
          total_gem_weight == o.total_gem_weight &&
          package_quantity == o.package_quantity &&
          item_dimensions == o.item_dimensions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [identifiers, color, edition, flavor, gem_type, golf_club_flex, hand_orientation, hardware_platform, material_type, metal_type, model, operating_system, product_type_subcategory, ring_size, shaft_material, scent, size, size_per_pearl, golf_club_loft, total_diamond_weight, total_gem_weight, package_quantity, item_dimensions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AmzSpApi::CatalogItemsApiModel.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
